In [1]:
import tensorflow as tf 

In [2]:
daily_sales_numbers = [21,22,-108,31,-1,32,34,31]

In [3]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [4]:
for sales in tf_dataset:
    print(sales.numpy())

21
22
-108
31
-1
32
34
31


In [5]:
for sales in tf_dataset:
    print(sales)

tf.Tensor(21, shape=(), dtype=int32)
tf.Tensor(22, shape=(), dtype=int32)
tf.Tensor(-108, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(34, shape=(), dtype=int32)
tf.Tensor(31, shape=(), dtype=int32)


In [6]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [7]:
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [8]:
tf_dataset = tf_dataset.filter(lambda x:x>0)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [9]:
tf_dataset = tf_dataset.map (lambda x: x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [10]:
tf_dataset = tf_dataset.shuffle(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2304
2232
2232
2448


In [11]:
tf_dataset = tf_dataset.shuffle(3)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2304
2232
2232
2448


In [12]:
for sales_batch in tf_dataset.batch(4):
    print(sales_batch.numpy())

[1512 1584 2448 2232]
[2304 2232]


In [13]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda x:x*72).shuffle(2).batch(2)

Cause: could not parse the source code of <function <lambda> at 0x000002B19BC9CC10>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names.
Match 0:
(lambda x: (x * 72))

Match 1:
(lambda x: (x > 0))

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: could not parse the source code of <function <lambda> at 0x000002B19BC9CC10>: found multiple definitions with identical signatures at the location. This error may be avoided by defining each lambda on a single line and with unique argument names.
Match 0:
(lambda x: (x * 72))

Match 1:
(lambda x: (x > 0))

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: could not parse the source code of <function <lambda> at 0x000002B19BC0A4C0>: found multiple definitions with identical signatures at the location. This error may be avoided b

In [14]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y:y*72).shuffle(2).batch(2)

for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1584 1512]
[2304 2448]
[2232 2232]


In [17]:
images_ds=tf.data.Dataset.list_files('images/*/*', shuffle=False)

for file in images_ds.take(5):
    print(file.numpy())

b'images\\Healthy Wheat\\00661.png'
b'images\\Healthy Wheat\\00671.jfif'
b'images\\Healthy Wheat\\00681.jfif'
b'images\\Healthy Wheat\\00721.jfif'
b'images\\Healthy Wheat\\00721.jpg'


In [18]:
class_names = ["Healthy Wheat","Unhealthy wheat"]

In [19]:
image_count = len(images_ds)
image_count

3073

In [21]:
train_size = int(image_count*0.8)

train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [22]:
len(train_ds)

2458

In [23]:
len(test_ds)

615

In [24]:
s = 'images\\Healthy Wheat\\00661.png'

s.split("\\")

['images', 'Healthy Wheat', '00661.png']

In [25]:
s.split("\\")[-2]

'Healthy Wheat'

In [26]:
def get_label(file_path):
    return file_path.split("\\")[-2]

In [30]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[-2]

In [33]:
def process_image(file_path):
    label = get_label(file_path)
    
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128,128])
    
    return img, label

In [27]:
for t in train_ds.take(4):
    print(t.numpy())

b'images\\Healthy Wheat\\00661.png'
b'images\\Healthy Wheat\\00671.jfif'
b'images\\Healthy Wheat\\00681.jfif'
b'images\\Healthy Wheat\\00721.jfif'


In [35]:
for img, label in train_ds.map(process_image).take(3):
    print("Image: ",img)
    print("Label: ",label)

Image:  tf.Tensor(
[[[ 53.60913    89.50513   151.84375  ]
  [ 54.952393   89.406494  152.46826  ]
  [ 57.79126    92.20874   155.91187  ]
  ...
  [ 53.670654   88.38501   146.59375  ]
  [ 52.593506   87.125     147.98462  ]
  [ 53.354004   87.95825   146.94287  ]]

 [[ 53.3125     89.82739   152.06201  ]
  [ 57.202393   89.48511   153.10938  ]
  [ 55.418213   92.109375  154.7356   ]
  ...
  [ 54.         89.296875  149.01196  ]
  [ 53.936768   88.75073   146.70459  ]
  [ 53.124268   87.68701   143.67163  ]]

 [[ 52.443115   88.890625  153.93188  ]
  [ 57.875      90.578125  154.       ]
  [ 54.3313     91.3313    154.       ]
  ...
  [ 55.493896   90.846924  149.44067  ]
  [ 54.235596   89.28003   150.50244  ]
  [ 52.140625   90.370605  148.02246  ]]

 ...

 [[117.683105  153.69751   204.79688  ]
  [120.578125  155.77759   206.49756  ]
  [121.49365   158.        208.       ]
  ...
  [  8.568848    4.153076    2.8562012]
  [ 13.883301    7.2438965   3.9819336]
  [ 20.762451   11.089355

In [37]:
train_ds = train_ds.map(process_image)
for img, label in train_ds.take(3):
    print("Image: ",img)
    print("Label: ",label)

Image:  tf.Tensor(
[[[ 53.60913    89.50513   151.84375  ]
  [ 54.952393   89.406494  152.46826  ]
  [ 57.79126    92.20874   155.91187  ]
  ...
  [ 53.670654   88.38501   146.59375  ]
  [ 52.593506   87.125     147.98462  ]
  [ 53.354004   87.95825   146.94287  ]]

 [[ 53.3125     89.82739   152.06201  ]
  [ 57.202393   89.48511   153.10938  ]
  [ 55.418213   92.109375  154.7356   ]
  ...
  [ 54.         89.296875  149.01196  ]
  [ 53.936768   88.75073   146.70459  ]
  [ 53.124268   87.68701   143.67163  ]]

 [[ 52.443115   88.890625  153.93188  ]
  [ 57.875      90.578125  154.       ]
  [ 54.3313     91.3313    154.       ]
  ...
  [ 55.493896   90.846924  149.44067  ]
  [ 54.235596   89.28003   150.50244  ]
  [ 52.140625   90.370605  148.02246  ]]

 ...

 [[117.683105  153.69751   204.79688  ]
  [120.578125  155.77759   206.49756  ]
  [121.49365   158.        208.       ]
  ...
  [  8.568848    4.153076    2.8562012]
  [ 13.883301    7.2438965   3.9819336]
  [ 20.762451   11.089355

In [36]:
def scale(image, label):
    return image/255, label

In [38]:
train_ds = train_ds.map(scale)
for image,label in train_ds.take(5):
    print("****Image: ",image.numpy()[0][0])
    print("****Label: ",label.numpy())

****Image:  [0.21023189 0.3510005  0.59546566]
****Label:  b'Healthy Wheat'
****Image:  [0.4963981  0.59051573 0.4571824 ]
****Label:  b'Healthy Wheat'
****Image:  [0.7519268 0.7854133 0.5811854]
****Label:  b'Healthy Wheat'
****Image:  [0.289022   0.46941414 0.31647298]
****Label:  b'Healthy Wheat'
****Image:  [0.16560969 0.18129596 0.08325674]
****Label:  b'Healthy Wheat'
